---
plonectl:
  debug_mode: false

instance:
  target: instance
  location_clienthome: "{{ target }}/var"
  location_log: "{{ target }}/var/log"
  wsgi_listen: localhost:8080
  wsgi_fast_listen: false
  wsgi_threads: 4
  wsgi_max_request_body_size: 1073741824
  wsgi_clear_untrusted_proxy_headers: false
  environment:
    zope_i18n_compile_mo_files: 'true'
    CHAMELEON_CACHE: "{{ target }}/var/cache"

  initial_user_name: admin
  initial_user_password: admin

  load_zcml:
    package_metas: []
    package_includes: []
    package_overrides: []
    locales_directory_location: ''
    include_file_location: ''
    overrides_file_location: ''
    resources_directory_location: ''

  dos_protection_available: true
  dos_protection_form_memory_limit: 1MB
  dos_protection_form_disk_limit: 1GB
  dos_protection_form_memfile_limit: 4KB

  db_storage: direct
  db_cache_size: 30000
  db_cache_size_bytes: ''
  db_large_record_size: ''
  db_pool_size: ''
  db_blobs_mode: cache
  db_blobs_location: "{{ target }}/var/blobs"
  db_filestorage_location: "{{ target }}/var/filestorage/Data.fs"
  db_filestorage_pack_keep_old: true
  db_filestorage_quota: ''
  db_filestorage_packer: ''
  db_filestorage_pack_gc: ''
  db_relstorage: ''
  db_relstorage_keep_history: true
  db_relstorage_read_only: false
  db_relstorage_create_schema: true
  db_relstorage_commit_lock_timeout: ''
  db_relstorage_commit_lock_id: ''
  db_relstorage_blob_cache_size_check_external: ''
  db_relstorage_blob_chunk_size: ''
  db_relstorage_cache_local_mb: ''
  db_relstorage_cache_local_object_max: ''
  db_relstorage_cache_local_compression: ''
  db_relstorage_cache_local_dir: ''
  db_relstorage_cache_prefix: ''
  db_relstorage_replica_conf: ''
  db_relstorage_ro_replica_conf: ''
  db_relstorage_replica_revert_when_stale: ''
  db_relstorage_replica_timeout: ''
  db_relstorage_postgresql_driver: ''
  db_relstorage_postgresql_dsn: ''
  db_relstorage_mysql_driver: ''
  db_relstorage_mysql_parameters: {}
  db_relstorage_orcale_user: ''
  db_relstorage_orcale_password: ''
  db_relstorage_orcale_dsn: ''
  db_relstorage_sqlite3_driver: ''
  db_relstorage_sqlite3_data_dir: "{{ target }}/var/sqlite3/"
  db_relstorage_sqlite3_gevent_yield_interval: ''
  db_relstorage_sqlite3_pragma: {}
  db_zeo_server: localhost:8100
  db_zeo_name: '1'
  db_zeo_client: ''
  db_zeo_var: ''
  db_zeo_cache_size: 128MB
  db_zeo_username: ''
  db_zeo_password: ''
  db_zeo_realm: ''
  db_zeo_read_only_fallback: false
  db_zeo_read_only: false
  db_zeo_drop_cache_rather_verify: false
  debug_mode: false
  verbose_security: false
  deprecation_warnings:
    - default
    - error
    - ignore
    - always
    - module
    - once
  profile_repoze: false
  profile_repoze_log_filename: ''
  profile_repoze_cachegrind_filename: ''
  profile_repoze_discard_first_request: ''
  profile_repoze_path: ''
  profile_repoze_flush_at_shutdown: ''
  profile_repoze_unwind: ''
